// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHPHqpW2_CnLff_KKM1pt5RtNJHPphiTY',
    appId: '1:844009676274:web:3d3d45786569eb495bdf6b',
    messagingSenderId: '844009676274',
    projectId: 'mtry-5f0e2',
    authDomain: 'mtry-5f0e2.firebaseapp.com',
    storageBucket: 'mtry-5f0e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp1L-cRVu-vwFD0mNItYDESz5pLW4Uuh4',
    appId: '1:844009676274:android:35bb781e125fd7985bdf6b',
    messagingSenderId: '844009676274',
    projectId: 'mtry-5f0e2',
    storageBucket: 'mtry-5f0e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz-BbAfNncE09r4s2miEfa4Iyr2u0hJDQ',
    appId: '1:844009676274:ios:9b9cf5c1e019276c5bdf6b',
    messagingSenderId: '844009676274',
    projectId: 'mtry-5f0e2',
    storageBucket: 'mtry-5f0e2.appspot.com',
    iosClientId: '844009676274-oti3rbjsaj9daunjbq463i502c9m6858.apps.googleusercontent.com',
    iosBundleId: 'com.example.medh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz-BbAfNncE09r4s2miEfa4Iyr2u0hJDQ',
    appId: '1:844009676274:ios:9b9cf5c1e019276c5bdf6b',
    messagingSenderId: '844009676274',
    projectId: 'mtry-5f0e2',
    storageBucket: 'mtry-5f0e2.appspot.com',
    iosClientId: '844009676274-oti3rbjsaj9daunjbq463i502c9m6858.apps.googleusercontent.com',
    iosBundleId: 'com.example.medh',
  );
}
